In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [7]:
a = a.reshape([1,-1])
a

array([[1, 2, 3]])

In [11]:
a = np.array((2,-1))
a

array([ 2, -1])

In [12]:
a.shape

(2,)

In [25]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [26]:
a = a.reshape((-1,2))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a[2,0] = 55
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

#zeros

In [17]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#ones

In [18]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#full

In [19]:
a = np.full((3,3),0)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
a = np.full((3,3),1)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#eye 单位矩阵

In [21]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
a = np.random.random((3,4))
a

array([[0.51626522, 0.43547081, 0.1034466 , 0.96058401],
       [0.42312828, 0.39089462, 0.20928759, 0.53384039],
       [0.23100497, 0.71465839, 0.63103017, 0.32989142]])

#indexing


In [31]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [34]:
a[-2:][1:3]#错误写法

array([[ 9, 10, 11, 12]])

In [35]:
a[1,-2]

7

In [36]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
b = a[-2:,1:3]
b

array([[ 6,  7],
       [10, 11]])

In [39]:
b.shape

(2, 2)

In [41]:
b = a[1,2]
b

7

In [42]:
b.shape

()

In [43]:
b = a[2:3,1:3]
b

array([[10, 11]])

In [44]:
b.shape

(1, 2)

In [45]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
a[np.arange(3),1]+=10
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [47]:
np.arange(3)

array([0, 1, 2])

In [48]:
np.arange(3,7)

array([3, 4, 5, 6])

In [50]:
a[np.arange(3),[1,1,1]]+=10
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [54]:
a[[0,1,2],[1,1,1]]+=10
a

array([[ 1, 52,  3,  4],
       [ 5, 56,  7,  8],
       [ 9, 60, 11, 12]])

In [56]:
result_index= a>10
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [57]:
a[result_index]

array([52, 56, 60, 11, 12])

In [58]:
a[a>10]

array([52, 56, 60, 11, 12])

#元素的数据类型

In [3]:
a = np.array([1,2])
a

array([1, 2])

In [5]:
a.dtype

dtype('float64')

In [4]:
a = np.array([1.1,2.2])
a

array([1.1, 2.2])

In [6]:
a = np.array([1,2.2])
a

array([1. , 2.2])

In [7]:
a.dtype

dtype('float64')

In [8]:
a = np.array([1.1,2.6])
a

array([1.1, 2.6])

In [9]:
a = np.array([1.1,2.6],dtype = np.int64)
a

array([1, 2], dtype=int64)

In [10]:
b = np.array(a,dtype=np.int64)
b

array([1, 2], dtype=int64)

#数学运算

In [11]:
a =np.array([[1,2],
           [3,4]])

In [12]:
b = np.array([[5,6],[6,5]])

In [13]:
a + b

array([[6, 8],
       [9, 9]])

In [14]:
np.add(a,b)

array([[6, 8],
       [9, 9]])

In [15]:
a-b

array([[-4, -4],
       [-3, -1]])

In [16]:
np.subtract(a,b)

array([[-4, -4],
       [-3, -1]])

In [17]:
a*b

array([[ 5, 12],
       [18, 20]])

In [18]:
np.multiply(a,b)

array([[ 5, 12],
       [18, 20]])

In [19]:
a/b

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [20]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [21]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [22]:
a

array([[1, 2],
       [3, 4]])

In [23]:
b =np.array([[1,2,3],
             [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a.dot(b)#叉乘

array([[ 9, 12, 15],
       [19, 26, 33]])

In [25]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

#sum

In [27]:
a

array([[1, 2],
       [3, 4]])

In [26]:
np.sum(a)

10

In [28]:
np.sum(a,axis=0)#列

array([4, 6])

In [29]:
np.sum(a,axis=1)#行

array([3, 7])

In [30]:
np.mean(a)#平均数

2.5

In [31]:
np.mean(a,axis=0)#列平均数

array([2., 3.])

In [32]:
np.mean(a,axis=1)#行

array([1.5, 3.5])

#uniform随机指定范围

In [33]:
np.random.uniform(3,4)

3.322827562500688

In [34]:
np.random.uniform(1,100)

33.12539896708073

#tile元素重复出现次数

In [35]:
a

array([[1, 2],
       [3, 4]])

In [36]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [37]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [38]:
np.tile(a,(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

#argsort排序

In [39]:
a = np.array([[3,6,4,1],
             [5,10,1,3]])
a

array([[ 3,  6,  4,  1],
       [ 5, 10,  1,  3]])

In [41]:
a.argsort()

array([[3, 0, 2, 1],
       [2, 3, 0, 1]], dtype=int64)

In [42]:
a.argsort(axis = 0)

array([[0, 0, 1, 0],
       [1, 1, 0, 1]], dtype=int64)

In [43]:
a.T

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [ 1,  3]])

#广播

In [3]:
a = np.array([[1,2,3],
             [2,3,4],
            [12,31,22],
            [2,2,2]])

In [4]:
b = np.array([1,2,3])
for i in range(4):
    a[:,:] +=b
a

array([[ 5, 10, 15],
       [ 6, 11, 16],
       [16, 39, 34],
       [ 6, 10, 14]])

In [5]:
a+np.tile(b,(4,1))

array([[ 6, 12, 18],
       [ 7, 13, 19],
       [17, 41, 37],
       [ 7, 12, 17]])

In [6]:
a+b

array([[ 6, 12, 18],
       [ 7, 13, 19],
       [17, 41, 37],
       [ 7, 12, 17]])